services:
  # Init container to generate mailcow.conf from template
  config-generator:
    image: alpine:latest
    volumes:
      - ./:/mailcow
    environment:
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DBROOT=${DBROOT}
      - REDISPASS=${REDISPASS}
      - SOGO_URL_ENCRYPTION_KEY=${SOGO_URL_ENCRYPTION_KEY}
    command: >
      sh -c "
        apk add --no-cache gettext &&
        envsubst < /mailcow/mailcow.conf.template > /mailcow/mailcow.conf &&
        chmod 600 /mailcow/mailcow.conf &&
        ln -sf mailcow.conf /mailcow/.env
      "
    restart: "no"

  # Make other services depend on config generation
  unbound-mailcow:
    depends_on:
      - config-generator

  mysql-mailcow:
    depends_on:
      - config-generator
      - unbound-mailcow
      - netfilter-mailcow