services:
  # Init container to generate mailcow.conf from template
  config-generator:
    image: alpine:latest
    volumes:
      - ./:/mailcow
    environment:
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME:-mail.tiuc.edu.ng}
      - DBNAME=${DBNAME:-mailcodb}
      - DBUSER=${DBUSER:-mailcodbusr}
      - DBPASS=${DBPASS:-y41AYnaGyd}
      - DBROOT=${DBROOT:-y41AYnaGyd}
      - REDISPASS=${REDISPASS:-py41AYnaGydiglOR3C}
      - SOGO_URL_ENCRYPTION_KEY=${SOGO_URL_ENCRYPTION_KEY:-py41AYnaGydiglO}
    command: >
      sh -c "
        apk add --no-cache gettext &&
        envsubst < /mailcow/mailcow.conf.template > /mailcow/mailcow.conf &&
        chmod 600 /mailcow/mailcow.conf &&
        ln -sf mailcow.conf /mailcow/.env
      "
    restart: "no"

  # Make other services depend on config generation
  unbound-mailcow:
    depends_on:
      config-generator:
        condition: service_completed_successfully

  mysql-mailcow:
    depends_on:
      config-generator:
        condition: service_completed_successfully
      unbound-mailcow:
        condition: service_started
      netfilter-mailcow:
        condition: service_started