services:
  # Init container to generate SSL certificates
  ssl-generator:
    image: alpine:latest
    volumes:
      - ./data/assets/ssl:/ssl
    command: >
      sh -c "
        apk add --no-cache openssl &&
        mkdir -p /ssl &&
        openssl req -x509 -newkey rsa:4096 -keyout /ssl/key.pem -out /ssl/cert.pem -days 365 -nodes -subj '/C=NG/ST=Lagos/L=Lagos/O=TIUC/OU=IT/CN=mail.tiuc.edu.ng' &&
        chmod 600 /ssl/key.pem /ssl/cert.pem
      "
    restart: "no"

  # Make nginx depend on SSL generation
  nginx-mailcow:
    depends_on:
      ssl-generator:
        condition: service_completed_successfully